-- GeneHub Seed Data
-- ============================================
-- This file intentionally empty.
-- 
-- Each user starts with a clean slate.
-- All data is user-specific and isolated via RLS policies.
-- API call results are cached in the shared api_cache table.
-- ============================================

-- No preloaded examples - users create their own data
-- Users are created via authentication
-- Sample notes would be created per-user
-- ============================================
